export const JobListingMapping = {
  positionTitle: 'position_title',
  experienceRequired: 'experience_required',
  positionType: 'position_type',
  workingArrangement: 'working_arrangement',
  positionCategory: 'position_category',
  technologies: 'technologies',
  'compensation.lower': 'comp_lower',
  'compensation.upper': 'comp_upper',
  'compensation.period': 'comp_period',
  'compensation.hasEquity': 'comp_has_equity',
  'compensation.hasBonus': 'comp_has_bonus',
  'compensation.hasCrypto': 'comp_has_crypto',
  'compensation.hasOther': 'comp_has_other',
  'compensation.equity': 'comp_equity',
  'compensation.annualBonus': 'comp_bonus',
  'compensation.crypto': 'comp_crypto',
  'compensation.currency': 'comp_currency',
  'compensation.other': 'comp_other',
  companyName: 'company_name',
  companyLogo: 'company_logo',
  companyLocation: 'company_location',
  remoteOnlyLocation: 'company_remote_only',
  contactEmail: 'contact_email_or_site',
  invoiceEmail: 'invoice_email',
  organisationFocus: 'organisation_focus',
  companyWebsite: 'company_website',
  organisationType: 'organisation_type',
  jobDescription: 'job_description',
};

export const JobListingMetadataMapping = {
  id: 'id',
  approved: 'approved',
  hidden: 'hidden',
  hashReceipt: 'hash_receipt',
  dateCreated: 'date_created',
};
